import type { Stop } from '@/lib/types';

/**
 * Taslak durak verileri — saha doğrulaması bekleniyor.
 * Gerçek usta isimleri, adresler veya hikâyeler kullanılmamıştır.
 * Her durak isPublished: false ve permissionConfirmed: false olarak işaretlenmiştir.
 */
export const MOCK_STOPS: Stop[] = [
  /* ── Katman 01 · Kağıt Sanatı ── */
  {
    slug: 'kagit-sanati-durak-01',
    name: 'Mücellithane (Taslak)',
    craft: 'Mücellit — kitap ciltleme',
    district: 'Ulus',
    layerSlug: 'kagit-sanati',
    shortDescription: 'Geleneksel ciltleme atölyesi. Saha doğrulaması bekleniyor.',
    visitStatus: 'unknown',
    permissionConfirmed: false,
    isPublished: false,
    mapX: 25,
    mapY: 30,
  },
  {
    slug: 'kagit-sanati-durak-02',
    name: 'Hattat Atölyesi (Taslak)',
    craft: 'Hat — geleneksel yazı sanatı',
    district: 'Hamamönü',
    layerSlug: 'kagit-sanati',
    shortDescription: 'Hat sanatı icra edilen atölye. Saha doğrulaması bekleniyor.',
    visitStatus: 'unknown',
    permissionConfirmed: false,
    isPublished: false,
    mapX: 55,
    mapY: 45,
  },
  {
    slug: 'kagit-sanati-durak-03',
    name: 'Tezhip Atölyesi (Taslak)',
    craft: 'Tezhip — süsleme sanatı',
    district: 'Altındağ',
    layerSlug: 'kagit-sanati',
    shortDescription: 'Tezhip ve el yazması süsleme çalışmaları. Saha doğrulaması bekleniyor.',
    visitStatus: 'unknown',
    permissionConfirmed: false,
    isPublished: false,
    mapX: 75,
    mapY: 65,
  },

  /* ── Katman 02 · Nesneyi Onaranlar ── */
  {
    slug: 'nesneyi-onaranlar-durak-01',
    name: 'Saat Tamircisi (Taslak)',
    craft: 'Analog saat tamiri',
    district: 'Ulus',
    layerSlug: 'nesneyi-onaranlar',
    shortDescription: 'Mekanik saat onarım atölyesi. Saha doğrulaması bekleniyor.',
    visitStatus: 'unknown',
    permissionConfirmed: false,
    isPublished: false,
    mapX: 30,
    mapY: 55,
  },
  {
    slug: 'nesneyi-onaranlar-durak-02',
    name: 'Kasket Ustası (Taslak)',
    craft: 'Şapka yapımı ve tamiri',
    district: 'Kale İçi',
    layerSlug: 'nesneyi-onaranlar',
    shortDescription: 'Geleneksel kasket yapımı ve onarımı. Saha doğrulaması bekleniyor.',
    visitStatus: 'unknown',
    permissionConfirmed: false,
    isPublished: false,
    mapX: 50,
    mapY: 25,
  },
  {
    slug: 'nesneyi-onaranlar-durak-03',
    name: 'Deri Atölyesi (Taslak)',
    craft: 'Deri işçiliği — çanta ve kemer',
    district: 'Çayyolu',
    layerSlug: 'nesneyi-onaranlar',
    shortDescription: 'Deri ürünleri onarım ve üretim atölyesi. Saha doğrulaması bekleniyor.',
    visitStatus: 'unknown',
    permissionConfirmed: false,
    isPublished: false,
    mapX: 80,
    mapY: 70,
  },

  /* ── Katman 03 · Geleneksel El Sanatları ── */
  {
    slug: 'geleneksel-el-sanatlari-durak-01',
    name: 'Dokuma Atölyesi (Taslak)',
    craft: 'Dokuma — halı ve kilim',
    district: 'Hacı Bayram',
    layerSlug: 'geleneksel-el-sanatlari',
    shortDescription: 'Geleneksel halı ve kilim dokuma atölyesi. Saha doğrulaması bekleniyor.',
    visitStatus: 'unknown',
    permissionConfirmed: false,
    isPublished: false,
    mapX: 40,
    mapY: 60,
  },
  {
    slug: 'geleneksel-el-sanatlari-durak-02',
    name: 'Çini Atölyesi (Taslak)',
    craft: 'Çini — seramik sanatı',
    district: 'Samanpazarı',
    layerSlug: 'geleneksel-el-sanatlari',
    shortDescription: 'El yapımı çini ve seramik üretimi. Saha doğrulaması bekleniyor.',
    visitStatus: 'unknown',
    permissionConfirmed: false,
    isPublished: false,
    mapX: 60,
    mapY: 35,
  },
  {
    slug: 'geleneksel-el-sanatlari-durak-03',
    name: 'Cam Ustası (Taslak)',
    craft: 'Cam sanatı — üfleme cam',
    district: 'Ayrancı',
    layerSlug: 'geleneksel-el-sanatlari',
    shortDescription: 'Üfleme cam tekniğiyle üretim yapan atölye. Saha doğrulaması bekleniyor.',
    visitStatus: 'unknown',
    permissionConfirmed: false,
    isPublished: false,
    mapX: 20,
    mapY: 80,
  },

  /* ── Katman 04 · Metal – Ahşap ── */
  {
    slug: 'metal-ahsap-durak-01',
    name: 'Bıçakçı Dükkanı (Taslak)',
    craft: 'Bıçakçılık — el yapımı bıçak',
    district: 'Hacı Bayram',
    layerSlug: 'metal-ahsap',
    shortDescription: 'Geleneksel bıçak yapım ve bileme atölyesi. Saha doğrulaması bekleniyor.',
    visitStatus: 'unknown',
    permissionConfirmed: false,
    isPublished: false,
    mapX: 35,
    mapY: 40,
  },
  {
    slug: 'metal-ahsap-durak-02',
    name: 'Tesbih Atölyesi (Taslak)',
    craft: 'Tesbih ustası — ahşap ve kehribar',
    district: 'Kale',
    layerSlug: 'metal-ahsap',
    shortDescription: 'El yapımı tesbih üretim ve onarım atölyesi. Saha doğrulaması bekleniyor.',
    visitStatus: 'unknown',
    permissionConfirmed: false,
    isPublished: false,
    mapX: 70,
    mapY: 20,
  },
  {
    slug: 'metal-ahsap-durak-03',
    name: 'Sedef Atölyesi (Taslak)',
    craft: 'Sedef işlemeciliği',
    district: 'Gölbaşı',
    layerSlug: 'metal-ahsap',
    shortDescription: 'Ahşap üzerine sedef kakma işçiliği. Saha doğrulaması bekleniyor.',
    visitStatus: 'unknown',
    permissionConfirmed: false,
    isPublished: false,
    mapX: 50,
    mapY: 85,
  },
];

/** Belirli bir katmana ait durakları filtreler. */
export const stopsByLayer = (layerSlug: string): Stop[] =>
  MOCK_STOPS.filter((s) => s.layerSlug === layerSlug);
